{% set name = "jobard-api" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_api/-/archive/{{ version }}/jobard_api-{{ version }}.tar.gz
  sha256: 5c2f2211944e6e5fb066b6b4849fd0a5d586d81b330dffbfa09b145db2e9fe82

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >=3.8
    - fastapi >=0.7
    - sqlalchemy >=1.4.25
    - psycopg2-binary >=2.8.6
    - databases >=0.5.3,<0.6
    - asyncpg >=0.25.0
    - uvicorn >=0.15.0
    - alembic >=1.7.5,<1.8

test:
  imports:
    - jobard_api

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_api
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Jobard API to submit and follow the execution of jobs.


extra:
  recipe-maintainers:
    - marie59
    - criou-cg
