{% set name = "jobard-api" %}
{% set version = "1.6.2" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.ifremer.fr/jobard/jobard_api/-/archive/{{ version }}/jobard_api-{{ version }}.tar.gz
  sha256: 113e62db566c0569af95a9f1d05208c46bfd4072eaa6a94bbfc33850ad4e1fb4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }}
    - fastapi >=0.7
    - sqlalchemy >=1.4.25
    - psycopg2-binary >=2.8.6
    - databases >=0.5.3,<0.6
    - asyncpg >=0.25.0
    - uvicorn >=0.15.0
    - alembic >=1.7.5,<1.8
    - pdrops::alembic-postgresql-enum >=1.3.0,<2.0.0

test:
  imports:
    - jobard_api

about:
  home: https://gitlab.ifremer.fr/jobard/jobard_api
  license: LGPL-3.0-only
  license_file: LICENSE
  summary: Jobard API to submit and follow the execution of jobs.


extra:
  recipe-maintainers:
    - marie59
    - criou-cg
